#访问根路径

#应用名称
spring:
  application:
    name: springboot-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhangfan?serverTimezone=UTC
    password: root
    username: root
    filer: wall,stat
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
      initial-size: 5
  #访问端口号
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/*Mapper.xml
